version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_flask_app
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: my_database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
